---
name: Rust source coverage
description: Docker github action that runs cargo test while gathering source-based coverage data
branding:
  icon: play-circle
  color: black
inputs:
  working_directory:
    description: Go to this directory before running the action
    default: ''
  dependencies_debian:
    description: Dependencies as Debian packages to install; used if defined
    default: ''
  output_type:
    description: Output type to pass to grcov
    default: ''
  output_path:
    description: Output path to pass to grcov and set as report variable
    default: ''
  test_args:
    description: Arguments to pass to the test
  doctest:
    description: Run documentation testing; true or false
    default: true
outputs:
  report:
    description: Name of report file, for compatibility with rust-grcov
runs:
  using: 'docker'
  image: 'Dockerfile'
