#!/bin/bash
# Copyright (C) 2021 Leandro Lisboa Penz <lpenz@lpenz.org>
# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.

if [ -n "$INPUT_DEPENDENCIES_DEBIAN" ]; then
    function install_dependencies {
        su - -c "apt-get update && apt-get install --no-install-recommends -y $INPUT_DEPENDENCIES_DEBIAN"
    }
else
    function install_dependencies {
        : no Debian packages to install
    }
fi

ARGS=()

if [ -n "$INPUT_OUTPUT_TYPE" ]; then
    ARGS+=( "--$INPUT_OUTPUT_TYPE" )
fi

if [ -n "$INPUT_OUTPUT_PATH" ]; then
    OUTPUT_PATH="$INPUT_OUTPUT_PATH"
    ARGS+=( --output-path "$OUTPUT_PATH" )
elif [ -z "$INPUT_OUTPUT_TYPE" ]; then
    # Default if no output_type was specified either
    OUTPUT_PATH="lcov.info"
    ARGS+=( --lcov --output-path "$OUTPUT_PATH" )
fi

export RUSTC_BOOTSTRAP
export CARGO_INCREMENTAL
export RUSTFLAGS
export RUSTDOCFLAGS
export RUST_BACKTRACE

set -e -x

install_dependencies

RUSTC_BOOTSTRAP='1' # enable -Z flags in stable
CARGO_INCREMENTAL='0'
RUSTFLAGS='-Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
RUSTDOCFLAGS="$RUSTFLAGS"
RUST_BACKTRACE=1

cargo llvm-cov --workspace clean
cargo llvm-cov --workspace --all-features --no-fail-fast --no-report
cargo llvm-cov --workspace --all-features --no-fail-fast --no-report --doc
cargo llvm-cov --no-run --doctests "${ARGS[@]}"
cargo llvm-cov --no-run --doctests

if [ -n "$OUTPUT_PATH" ]; then
    echo "::set-output name=report::$OUTPUT_PATH"
fi

