#!/bin/bash
# Copyright (C) 2021 Leandro Lisboa Penz <lpenz@lpenz.org>
# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.

if [ -n "$INPUT_DEPENDENCIES_DEBIAN" ]; then
    function install_dependencies {
        su - -c "apt-get update && apt-get install --no-install-recommends -y $INPUT_DEPENDENCIES_DEBIAN"
    }
else
    function install_dependencies {
        : no Debian packages to install
    }
fi

GRCOV=( grcov . \
              -s . \
              --binary-path ./target/debug/ \
              --ignore "/*" --ignore "../*" \
              --branch --ignore-not-existing \
      )

if [ -n "$INPUT_OUTPUT_TYPE" ]; then
    GRCOV+=( -t "$INPUT_OUTPUT_TYPE" )
fi

if [ -n "$INPUT_OUTPUT_PATH" ]; then
    GRCOV+=( -o "$INPUT_OUTPUT_PATH" )
    OUTPUT_PATH="$INPUT_OUTPUT_PATH"
elif [ -z "$INPUT_OUTPUT_TYPE" ]; then
    # Default if no output_type was specified either
    GRCOV+=( -o lcov.info )
    OUTPUT_PATH="lcov.info"
fi

set -e -x

install_dependencies

export CARGO_INCREMENTAL='0'
export RUSTFLAGS='-Zinstrument-coverage -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
export RUSTDOCFLAGS='-Zinstrument-coverage -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests -Z unstable-options --persist-doctests target/debug/doctestbins'
export LLVM_PROFILE_FILE="coverage-%p-%m.profraw"
export RUST_BACKTRACE=1

cargo test --all-features --no-fail-fast

"${GRCOV[@]}"
if [ -n "$OUTPUT_PATH" ]; then
    echo "::set-output name=report::$OUTPUT_PATH"
fi

