#!/bin/bash
# Copyright (C) 2021 Leandro Lisboa Penz <lpenz@lpenz.org>
# This file is subject to the terms and conditions defined in
# file 'LICENSE', which is part of this source code package.

if [ -n "$INPUT_DEPENDENCIES_DEBIAN" ]; then
    function install_dependencies {
        su - -c "apt-get update && apt-get install --no-install-recommends -y $INPUT_DEPENDENCIES_DEBIAN"
    }
else
    function install_dependencies {
        : no Debian packages to install
    }
fi

TEST_ARGS=()
if [ -n "$INPUT_TEST_ARGS" ]; then
    IFS=' ' read -r -a testargs <<<"$INPUT_TEST_ARGS"
    TEST_ARGS+=("${testargs[@]}")
fi

OUTPUT_ARGS=()

if [ -n "$INPUT_OUTPUT_TYPE" ]; then
    OUTPUT_ARGS+=("--$INPUT_OUTPUT_TYPE")
fi

if [ -n "$INPUT_DOCTEST" ]; then
    DOCTEST="$INPUT_DOCTEST"
else
    if grep -q '^doctest\s\+=\s\+false' Cargo.toml; then
        DOCTEST=false
    else
        DOCTEST=true
    fi
fi

if [ -n "$INPUT_OUTPUT_PATH" ]; then
    OUTPUT_PATH="$INPUT_OUTPUT_PATH"
    OUTPUT_ARGS+=(--output-path "$OUTPUT_PATH")
elif [ -z "$INPUT_OUTPUT_TYPE" ]; then
    # Default if no output_type was specified either
    OUTPUT_PATH="lcov.info"
    OUTPUT_ARGS+=(--lcov --output-path "$OUTPUT_PATH")
fi

export RUSTC_BOOTSTRAP
export CARGO_INCREMENTAL
export RUSTFLAGS
export RUSTDOCFLAGS
export RUST_BACKTRACE

set -e -x

install_dependencies

CARGO_INCREMENTAL='0'
RUSTFLAGS='-Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests'
RUSTDOCFLAGS="$RUSTFLAGS"
RUST_BACKTRACE=1

su -p -c "cargo llvm-cov --workspace clean"

# Run regular test:
cargo llvm-cov --workspace --all-features --no-fail-fast --no-report -- "${TEST_ARGS[@]}"
if [ "$DOCTEST" = "true" ]; then
    # Run doc tests:
    cargo llvm-cov --workspace --all-features --no-fail-fast --no-report --doc -- "${TEST_ARGS[@]}"
else
    : skipping coverage of doc tests
fi
# Generate report including doc tests:
cargo llvm-cov --no-run --doctests "${OUTPUT_ARGS[@]}"
# Print summary including doc tests:
cargo llvm-cov --no-run --doctests

if [ -n "$OUTPUT_PATH" ]; then
    sed -i "s@$GITHUB_WORKSPACE/@@" "$OUTPUT_PATH"

    echo "::set-output name=report::$OUTPUT_PATH"

    if [ -n "$RUNNER_DEBUG" ]; then
        cat "$OUTPUT_PATH"
    fi
fi
